name: Notify Discord on Stage Push/Merge

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          curl -H "Content-Type: application/json" \
               -d "{\"username\": \"GitHub\", \"content\": \"kurwa.\"}" \
               $DISCORD_WEBHOOK_URL
