name: Notify Discord on Stage Push/Merge

on:
  pull_request:
    types: [closed]

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          PR_AUTHOR=${{ github.event.pull_request.user.login }}
          SOURCE_BRANCH=${{ github.event.pull_request.head.ref }}
          TARGET_BRANCH=${{ github.event.pull_request.base.ref }}

          MESSAGE="Pull request from \`${SOURCE_BRANCH}\` merged into \`${TARGET_BRANCH}\` by ${PR_AUTHOR}.\nПроводиться редеплой, сайт має запрацювати протягом 2-5 хвилин."

          echo "Sending message to Discord..."

          curl -H "Content-Type: application/json" \
               -d "{\"username\": \"Git\", \"content\": \"$MESSAGE\"}" \
               ${{ secrets.DISCORD_WEBHOOK_URL }}
